### ISSUE TITLE
Error: Invalid header received

### ISSUE THREAD

**Issue by pavanyogi** [hypercore-protocol/p2p-multiwriter-with-autobase#13]
We are getting the following errors during the execution of the code. 

```
pavany@u-16:~/.../01$ node client.js 
Connected to server
/home/pavany/Documents/aux/qbix/hypercore/HypercorePlayground/p2p-multiwriter-with-autobase/01/node_modules/@hyperswarm/secret-stream/index.js:212
          this.destroy(new Error('Invalid header received'))
                       ^

**Error: Invalid header received**
    at NoiseSecretStream._incoming (/home/pavany/Documents/aux/qbix/hypercore/HypercorePlayground/p2p-multiwriter-with-autobase/01/node_modules/@hyperswarm/secret-stream/index.js:212:24)
    at NoiseSecretStream._onrawdata (/home/pavany/Documents/aux/qbix/hypercore/HypercorePlayground/p2p-multiwriter-with-autobase/01/node_modules/@hyperswarm/secret-stream/index.js:148:18)
    at Connection.emit (events.js:315:20)
    at addChunk (/home/pavany/Documents/aux/qbix/hypercore/HypercorePlayground/p2p-multiwriter-with-autobase/01/node_modules/readable-stream/lib/_stream_readable.js:298:12)
    at readableAddChunk (/home/pavany/Documents/aux/qbix/hypercore/HypercorePlayground/p2p-multiwriter-with-autobase/01/node_modules/readable-stream/lib/_stream_readable.js:280:11)
    at Connection.Readable.push (/home/pavany/Documents/aux/qbix/hypercore/HypercorePlayground/p2p-multiwriter-with-autobase/01/node_modules/readable-stream/lib/_stream_readable.js:241:10)
    at Connection._onread (/home/pavany/Documents/aux/qbix/hypercore/HypercorePlayground/p2p-multiwriter-with-autobase/01/node_modules/utp-native/lib/connection.js:143:8)
Emitted 'error' event on NoiseSecretStream instance at:
    at WritableState.afterDestroy (/home/pavany/Documents/aux/qbix/hypercore/HypercorePlayground/p2p-multiwriter-with-autobase/01/node_modules/streamx/index.js:442:19)
    at NoiseSecretStream._destroy (/home/pavany/Documents/aux/qbix/hypercore/HypercorePlayground/p2p-multiwriter-with-autobase/01/node_modules/@hyperswarm/secret-stream/index.js:367:5)
    at WritableState.updateNonPrimary (/home/pavany/Documents/aux/qbix/hypercore/HypercorePlayground/p2p-multiwriter-with-autobase/01/node_modules/streamx/index.js:189:16)
    at WritableState.update (/home/pavany/Documents/aux/qbix/hypercore/HypercorePlayground/p2p-multiwriter-with-autobase/01/node_modules/streamx/index.js:174:70)
    at WritableState.updateWriteNT (/home/pavany/Documents/aux/qbix/hypercore/HypercorePlayground/p2p-multiwriter-with-autobase/01/node_modules/streamx/index.js:482:8)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
pavany@u-16:~/.../01$ 
```

**Comment by pavanyogi** [comment]
With the latest (LTS) node js version (v16.13.1), this error resolved.
